---
title: "assignment2"
author: "Jake Eisaguirre"
date: '`r format(Sys.time(), "%m/%d/%Y")`'
output: 
  pdf_document:
    toc: false
    number_sections: yes
header-includes:
  - \setlength{\parindent}{1em}
  - \usepackage{float}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(LexisNexisTools)
library(syuzhet)
library(sentimentr)
library(tidytext)
library(lubridate)
```

```{r}

my_files <- list.files(pattern = ".docx", path = here(),
                       full.names = TRUE, recursive = TRUE, ignore.case = TRUE)

dat <- lnt_read(my_files) #Object of class 'LNT output'
```

```{r}
meta_df <- dat@meta
articles_df <- dat@articles
paragraphs_df <- dat@paragraphs

dat2<- data_frame(element_id = seq(1:length(meta_df$Headline)), Date = meta_df$Date, Headline = meta_df$Headline)

paragraphs_dat <- data_frame(element_id = paragraphs_df$Art_ID, Text  = paragraphs_df$Paragraph)

dat3 <- inner_join(dat2,paragraphs_dat, by = "element_id")
```

```{r}
mytext <- get_sentences(dat3$Text)

sent <- sentiment(mytext)
```

```{r}
sent_df <- inner_join(dat3, sent, by = "element_id")

sentiment <- sentiment_by(sent_df$Text)


sent_df %>%
  arrange(sentiment)
```

```{r}
nrc_sent <- get_sentiments('nrc')

text_words <- dat3  %>%
  unnest_tokens(output = word, input = Text, token = 'words')
 
sent_words <- text_words%>% #break text into individual words
  anti_join(stop_words, by = 'word') %>% 
  inner_join(nrc_sent, by = 'word') %>% 
  filter(!sentiment %in% c("positive", "negative")) %>% 
  mutate(Date = as_date(Date))

sent_word_count <- sent_words %>% 
  group_by(Date, sentiment) %>% 
  count(sentiment) %>% 
  ungroup() %>% 
  group_by(Date) %>% 
  mutate(n_max = sum(n),
         percent = round((n / n_max) * 100, 2))


```


```{r}

ggplot(data = sent_word_count) +
  geom_line(aes(x = Date, y = percent, fill = sentiment, color = sentiment)) +
  theme_classic() +
  labs(title = "Sentiment Surrounding Wildfires for 2022-03-16 to 2022-04-13",
       y = "Percent",
       x = "Date")

```

